version: '3.8'
services:
    # PostgreSQL Database with pgvector extension
    database:
        image: pgvector/pgvector:pg15
        environment:
            POSTGRES_DB: taskmanager
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 10s
            retries: 5
    # Backend API
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        environment:
            DB_HOST: database
            DB_PORT: 5432
            DB_NAME: taskmanager
            DB_USER: postgres
            DB_PASSWORD: password
            NODE_ENV: production
        depends_on:
            database:
                condition: service_healthy
        restart: unless-stopped
    # Frontend React App
    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        environment:
            REACT_APP_API_URL: http://localhost:5000/api
        depends_on:
            - backend
        restart: unless-stopped
volumes:
    postgres_data: